# Generated by Django 5.2.8 on 2025-12-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0003_instructor_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=100),
        ),
    ]
