# Generated by Django 5.2.8 on 2025-12-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructor', '0004_instructor_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='status',
        ),
    ]
