# Generated by Django 5.2.8 on 2025-12-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Exam', '0002_alter_exam_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_by',
        ),
    ]
