# Generated by Django 4.2.26 on 2025-11-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_alter_classroom_unique_together_alter_classroom_cls_and_more'),
        ('student', '0002_remove_student_cls_remove_student_sec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.section'),
        ),
    ]
