# Generated by Django 4.2.26 on 2025-11-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('lab', 'Lab')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls', models.CharField(max_length=20)),
                ('sec', models.CharField(max_length=5)),
            ],
            options={
                'unique_together': {('cls', 'sec')},
            },
        ),
    ]
