# Generated by Django 4.2.26 on 2025-11-27 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='cls',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='sec',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(max_length=255)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Academics.classroom')),
            ],
            options={
                'unique_together': {('cls', 'sec')},
            },
        ),
    ]
