# Generated by Django 5.2.8 on 2025-11-28 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_alter_classroom_unique_together_alter_classroom_cls_and_more'),
        ('instructor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('class_teacher', 'Class Teacher'), ('assistant_teacher', 'Assistant Teacher'), ('hod', 'HOD')], max_length=20)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.classroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
            ],
            options={
                'unique_together': {('classroom', 'section', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='AssignSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.classroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructor.instructor')),
            ],
            options={
                'unique_together': {('classroom', 'section', 'subject')},
            },
        ),
    ]
