# Generated by Django 5.2.8 on 2025-12-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_assignclassteacher_assignsubject'),
        ('instructor', '0003_instructor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignsubject',
            name='teacher',
        ),
        migrations.AddField(
            model_name='assignsubject',
            name='teacher',
            field=models.ManyToManyField(related_name='academics_assignments', to='instructor.instructor'),
        ),
    ]
