# Generated by Django 5.2.8 on 2025-12-13 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Online_Exam', '0003_remove_exam_created_by'),
        ('student', '0003_remove_student_classroom_student_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_answer', models.CharField(blank=True, max_length=250, null=True)),
                ('correct_answer', models.CharField(max_length=250)),
                ('is_correct', models.BooleanField(default=False)),
                ('mark_obtained', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Exam.exam')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Exam.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Online_Exam.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
