# Generated by Django 5.2.8 on 2025-12-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review_Exam', '0002_examattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamrecord',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentexamrecord',
            name='total_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ExamAttempt',
        ),
    ]
