# Generated by Django 5.2.8 on 2025-12-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review_Exam', '0003_studentexamrecord_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexamrecord',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='studentexamrecord',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('not_started_yet', 'Not Started Yet'), ('expired', 'Expired')], default='not_started_yet', max_length=20),
        ),
    ]
